In [2]:
import torch
import torch.nn as nn

# 배치 크기, 문장 길이, 입력차원
x = torch.randn(1,5,10) # randn은 평균 0 표준편차 1인 난수 생성을 의미
#print(x)

rnn = nn.RNN(
    input_size = 10,
    hidden_size = 8,
    batch_first = True
)

output, hidden = rnn(x)
print(output.shape) # (1,5,8)
print(hidden.shape) # (1,1,8)


torch.Size([1, 5, 8])
torch.Size([1, 1, 8])


In [3]:
# LSTM 코드
import torch
import torch.nn as nn

x = torch.randn(1,5,10)

lstm = nn.LSTM(
    input_size = 10,
    hidden_size = 8,
    batch_first = True
)

output, (hidden, cell) = lstm(x)

print(output.shape) # (1,5,8)
print(hidden.shape) # (1,1,8)
print(cell.shape) # (1,1,8)


torch.Size([1, 5, 8])
torch.Size([1, 1, 8])
torch.Size([1, 1, 8])


In [ ]:
# Forget Gate 코드

# 현재 값 입력
x = torch.randn(1,8)

# 이전 hiiden state
h_prev = torch.randn(1,10)

# 이전 cell_state
c_prev = torch.randn(1,8)

# x와 h를 연결
combined = torch.cat((x,h_prev),dim = 1)

# Forget Gate용 가중치
forget_layer = nn.Linear(18,8)

# Forget Gate 계산
f_score = forget_layer(combined) # 출력은 8차원으로 됨
#print(f_score)

# 시그모이드 적용ㅎ서 값 0~1 사이로 변환
forget_gate = torch.sigmoid(f_score)

# 이전 cell_state에 적용
cell = forget_gate * c_prev
print(cell)

tensor([[ 0.4665, -0.7646,  0.2916,  0.0829, -1.0022, -0.0308,  2.4110,  0.8746,
          1.1235, -0.8328,  1.3782, -0.8516,  1.4775, -0.5093,  1.4394, -0.1726,
         -1.7265, -0.1404]])
tensor([[ 0.6068, -0.3892,  0.2961,  0.7612,  0.0072,  0.0919,  0.0636,  0.3007]],
       grad_fn=<MulBackward0>)


In [ ]:
# Input Gate 코드

# 현재 값 입력
x = torch.randn(1,8)

# 이전 hiiden state
h_prev = torch.randn(1,10)

# 합쳐
combined = torch.cat((x,h_prev), dim = 1)

# Input Gate용 가중치
input_layer = nn.Linear(18,8)

# Input Gate 계산
input_gate = torch.sigmoid(input_layer(combined))

# 새로운 기억을 만들어
candidate_layer = nn.Linear(18,8)

# 새로운 기억 계산
candidate = torch.tanh(
    candidate_layer(combined)
)

# 완벽한 새로운 기억 생성
new_memory = input_gate * candidate

# 최종
cell = forget_gate * c_prev \
     + input_gate * candidate

print(cell)




tensor([[ 0.5570, -0.3307,  0.5756,  1.1046,  0.0871,  0.3875,  0.3410,  0.2270]],
       grad_fn=<AddBackward0>)


In [12]:
# Output Gate

output_layer = nn.Linear(18,8)

output_gate = torch.sigmoid(
    output_layer(combined)
)

# Output Gate 적용
cell_tanh = torch.tanh(cell)

h_new = output_gate * cell_tanh

print(h_new)

tensor([[ 0.1603, -0.0990,  0.2463,  0.4280,  0.0390,  0.1548,  0.1553,  0.0670]],
       grad_fn=<MulBackward0>)


In [13]:
# Attention 코드

Q = torch.randn(1,4)
K = torch.randn(3,4)
V = torch.randn(3,5)

# 점수를 계산
score = torch.matmul(Q,K.T)

# 가중치 계산
weights = torch.softmax(score, dim = -1)

# 출력
output = torch.matmul(weights,V)

print(output)

tensor([[ 0.4394,  0.8780,  0.9145, -0.6011, -0.1878]])
